server:
  port: 8264
  servlet:
    context-path: /ming-seckill

spring:
  application:
    name: seckill-service
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.155.89.175:3306/db_seckill_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 
    hikari:
      # 连接池名称
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间
      idle-timeout: 1800000
      # 最大连接数
      maximum-pool-size: 10
      # 连接最大存活时间
      max-lifetime: 3600000
      # 连接超时时间
      connection-timeout: 30000
      # 是否自动提交
      auto-commit: true
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  # Redis配置
  redis:
    host: 139.155.89.175
    port: 6379
    password:
    database: 0
    timeout: 6000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间
        max-wait: 5000ms
        # 最大空闲连接数
        max-idle: 20
        # 最小空闲连接数
        min-idle: 4

# MyBatis配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: ind.liuer.seckill.domain

# 日志配置
logging:
  level:
    ind.liuer.seckill.dao: debug

# 系统属性配置（自定义）
system:
  config:
    login-error-details: false
    login-cookie-name: UserToken
    login-cookie-max-age: 1800
    login-ignore-methods:
      - ind.liuer.seckill.controller.TestController.test
      - ind.liuer.seckill.controller.LoginController.login
